#-----------------------------------------------------------
# My deploy 
# Pastushenko Andrey
#------------------------------------------------------------



name: My-GitHubActions

env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME    : "flask-deploy-ver${{ github.sha }}"
 
on:
  push:
    branches: [ master ]
 
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from Testing job" 

      - name: Execure few commands
        run:
           echo "Hello Message1"
           echo "Hello Message1"
           echo "Appication name; ${{ env.APPLICATION_NAME}}" 
      
      
      - name: List currnt folder
        run : ls -la
        
        
      - name: Git clone my repo
        uses: actions/checout@v1
        
      - name: List currnt folder
        run : ls -la
      
      
  my_deploy:
    runs-on: ubuntu-latest
    needs  : [my_testing]
  
  
    steps:
     - name: Print Hello Massage in Deploy
       run : echo "Hello World from Deploy job" 
       
     - name: Printing Deployment package
       run : echo "Deplyo pakcage name is ${{ env.PACKAGE_NAME}}" 
  
     - name: Lets test some packages if they are here 1
       run : aws --version
       
     - name: Lets test some packages if they are here 2
       run : zip
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
